# Built on Windows 10 Home 20H2

version: '3.1'
services:
  php-fpm:
    build: ./php-fpm/
    container_name: "PHP-fpm"
    volumes:
      - ./nginx/web/:/usr/share/nginx/html/
  nginx:
    build: ./nginx/
    container_name: "Nginx"
    depends_on:
      - php-fpm
    ports: 
      - "49152:80"
    volumes:
      - ./nginx/web/:/usr/share/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  