# Built on Windows10(20H2)

version: '3.1'
services:
  adminer:
    build: ./adminer/
    container_name: "Adminer"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "49153:8080"
  php-fpm:
    build: ./php-fpm/
    container_name: "PHP-fpm"
    volumes:
      - ./nginx/html/:/usr/share/nginx/html/
  postgres:
    build: ./postgres/
    container_name: "Postgres"
    environment:
      POSTGRES_PASSWORD: "pass4develop"
      POSTGRES_USER:     "developer"
  nginx:
    build: ./nginx/
    container_name: "Nginx"
    depends_on:
      - php-fpm
    ports: 
      - "49152:80"
    volumes:
      - ./nginx/html/:/usr/share/nginx/html/
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf